CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS (
ID BIGINT AUTO_INCREMENT,
SALGADA VARCHAR (20),
DOCE VARCHAR (20),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZAS (
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR (50),
SABOR VARCHAR (50),
ACOMPANHAMENTO VARCHAR (40),
PRECO DOUBLE,
CLASSIFICACAO_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CLASSIFICACAO_ID) REFERENCES TB_CATEGORIAS (ID)
);

INSERT INTO TB_CATEGORIAS (SALGADA, DOCE)
VALUES ("Mucarela", "Morango");
INSERT INTO TB_CATEGORIAS (SALGADA, DOCE)
VALUES ("Calabresa", "Brigadeiro");
INSERT INTO TB_CATEGORIAS (SALGADA, DOCE)
VALUES ("Portuguesa", "Chocolate");
INSERT INTO TB_CATEGORIAS (SALGADA, DOCE)
VALUES ("Quatro Queijos", "Doce de Leite");
INSERT INTO TB_CATEGORIAS (SALGADA, DOCE)
VALUES ("Frango com Catupiry", "Sorvete");

INSERT INTO TB_PIZZAS (TIPO, SABOR, ACOMPANHAMENTO, PRECO, CLASSIFICACAO_ID)
VALUES ("Salgada", "Mucarela", "Refrigerante Guarana", 85.00, 1);
INSERT INTO TB_PIZZAS (TIPO, SABOR, ACOMPANHAMENTO, PRECO, CLASSIFICACAO_ID)
VALUES ("Salgada", "Frango com Catupiry", "Suco natural de maracuja", 80.00, 4);
INSERT INTO TB_PIZZAS (TIPO, SABOR, ACOMPANHAMENTO, PRECO, CLASSIFICACAO_ID)
VALUES ("Doce", "Brigadeiro", "Suco de abacaxi", 40.00, 2);
INSERT INTO TB_PIZZAS (TIPO, SABOR, ACOMPANHAMENTO, PRECO, CLASSIFICACAO_ID)
VALUES ("Salgada", "Calabresa", "Refrigerante Coca Cola", 85.00, 2);
INSERT INTO TB_PIZZAS (TIPO, SABOR, ACOMPANHAMENTO, PRECO, CLASSIFICACAO_ID)
VALUES ("Doce", "Morango", "Refrigerante Fanta Uva", 45.00, 1);
INSERT INTO TB_PIZZAS (TIPO, SABOR, ACOMPANHAMENTO, PRECO, CLASSIFICACAO_ID)
VALUES ("Doce", "Sorvete", "Suco natural de laranja", 42.00, 4);
INSERT INTO TB_PIZZAS (TIPO, SABOR, ACOMPANHAMENTO, PRECO, CLASSIFICACAO_ID)
VALUES ("Doce", "Chocolate", "Suco de manga", 43.00, 3);
INSERT INTO TB_PIZZAS (TIPO, SABOR, ACOMPANHAMENTO, PRECO, CLASSIFICACAO_ID)
VALUES ("Salgada", "Portuguesa", "Refrigerante Pepsi", 70.00, 4);

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PIZZAS;

SELECT * FROM TB_PIZZAS WHERE PRECO > 45.00;
SELECT * FROM TB_PIZZAS WHERE PRECO > 50.00 AND PRECO < 100.00;
SELECT * FROM TB_PIZZAS WHERE  SABOR LIKE "%M%";
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CLASSIFICACAO_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CLASSIFICACAO_ID = TB_CATEGORIAS.ID WHERE CLASSIFICACAO_ID = 2