CREATE DATABASE DB_CIDADE_DOS_VEGETAIS;
USE DB_CIDADE_DOS_VEGETAIS;

CREATE TABLE TB_CATEGORIAS (
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR (30),
VITAMINA VARCHAR (30),
PRIMARY KEY (ID)
);

SELECT * FROM TB_CATEGORIAS;

CREATE TABLE TB_PRODUTOS (
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (20),
QUANTIDADE INT,
PESO DOUBLE,
PRECO DOUBLE,
TABELA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (TABELA_ID) REFERENCES TB_CATEGORIAS (ID)
);

SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_CATEGORIAS (TIPO, VITAMINA)
VALUES ("Vegetal tipo Fruto", "Vitamina C");
INSERT INTO TB_CATEGORIAS (TIPO, VITAMINA)
VALUES ("Vegetal tipo Folha", "Vitamina A,B,C");
INSERT INTO TB_CATEGORIAS (TIPO, VITAMINA)
VALUES ("Vegetal tipo Flor", "Vitamina A, B");
INSERT INTO TB_CATEGORIAS (TIPO, VITAMINA)
VALUES ("Vegetal tipo Raiz", "Vitamina C");
INSERT INTO TB_CATEGORIAS (TIPO, VITAMINA)
VALUES ("Vegetal tipo Tuberculos", "Vitamina C, B");

INSERT INTO TB_PRODUTOS (NOME, QUANTIDADE, PESO, PRECO, TABELA_ID)
VALUES ("Cenourinha", "3", 500, 2.50, 4);
INSERT INTO TB_PRODUTOS (NOME, QUANTIDADE, PESO, PRECO, TABELA_ID)
VALUES ("Beterraba", 10, 150, 5.00, 4);
INSERT INTO TB_PRODUTOS (NOME, QUANTIDADE, PESO, PRECO, TABELA_ID)
VALUES ("Brocolis", 5, 400, 11.00, 3);
INSERT INTO TB_PRODUTOS (NOME, QUANTIDADE, PESO, PRECO, TABELA_ID)
VALUES ("Batata Doce", 10, 700, 22.00, 5);
INSERT INTO TB_PRODUTOS (NOME, QUANTIDADE, PESO, PRECO, TABELA_ID)
VALUES ("Maca", 15, 650, 25.00, 1);
INSERT INTO TB_PRODUTOS (NOME, QUANTIDADE, PESO, PRECO, TABELA_ID)
VALUES ("Couve Flor", 10, 400, 13.00, 3);
INSERT INTO TB_PRODUTOS (NOME, QUANTIDADE, PESO, PRECO, TABELA_ID)
VALUES ("Espinafre", 20, 900, 55.00, 2);
INSERT INTO TB_PRODUTOS (NOME, QUANTIDADE, PESO, PRECO, TABELA_ID)
VALUES ("Chuchu", 5, 400, 26.00, 1);

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50.00;
SELECT * FROM TB_PRODUTOS WHERE PRECO > 5 AND PRECO < 150;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.TABELA_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.TABELA_ID =TB_CATEGORIAS.ID WHERE TIPO = 4;