CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES (
ID BIGINT (10) AUTO_INCREMENT,
CATEGORIA VARCHAR (255) NOT NULL,
TIPO VARCHAR (255) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PERSONAGENS (
ID BIGINT (10) AUTO_INCREMENT,
NOME VARCHAR (255) NOT NULL,
HP INT,
ATQ INT,
DEF INT,
CLASSES_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CLASSES_ID) REFERENCES TB_CLASSES (ID)
);

INSERT INTO TB_CLASSES (CATEGORIA, TIPO)
VALUES ("Selvagem", "Dano");
INSERT INTO TB_CLASSES (CATEGORIA, TIPO)
VALUES ("Humano", "Tanker");
INSERT INTO TB_CLASSES (CATEGORIA, TIPO)
VALUES ("Alado", "Curador");
INSERT INTO TB_CLASSES (CATEGORIA, TIPO)
VALUES ("Guardiao", "Protetor");

SELECT * FROM TB_CLASSES;

INSERT INTO TB_PERSONAGENS (NOME, HP, ATQ, DEF, CLASSES_ID)
VALUES ("Zhongli", 8159, 210, 1950, 3);
INSERT INTO TB_PERSONAGENS (NOME, HP, ATQ, DEF, CLASSES_ID)
VALUES ("Itto", 5100, 550, 520, 2);
INSERT INTO TB_PERSONAGENS (NOME, HP, ATQ, DEF, CLASSES_ID)
VALUES ("Barbara", 5300, 650, 110, 5);
INSERT INTO TB_PERSONAGENS (NOME, HP, ATQ, DEF, CLASSES_ID)
VALUES ("Xiangling", 1450, 310, 355, 6);
INSERT INTO TB_PERSONAGENS (NOME, HP, ATQ, DEF, CLASSES_ID)
VALUES ("Ayato", 1500, 300, 540, 5);
INSERT INTO TB_PERSONAGENS (NOME, HP, ATQ, DEF, CLASSES_ID)
VALUES ("Xiao", 1490, 320, 550, 1);
INSERT INTO TB_PERSONAGENS (NOME, HP, ATQ, DEF, CLASSES_ID)
VALUES ("Sayu", 3500, 200, 300, 2);
INSERT INTO TB_PERSONAGENS (NOME, HP, ATQ, DEF, CLASSES_ID)
VALUES ("Ganyu", 3700, 309, 500, 1);

SELECT * FROM TB_CLASSES;
SELECT * FROM TB_PERSONAGENS;

SELECT * FROM TB_PERSONAGENS WHERE ATQ > 2000;
SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE "%C%";
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID =TB_CLASSES.ID;
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = CLASSES_ID WHERE TIPO = "Tanker";