CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS (
ID BIGINT AUTO_INCREMENT,
COSMETICO VARCHAR (30),
FUNCAO VARCHAR (30),
PRIMARY KEY (ID) 
);

CREATE TABLE TB_PRODUTOS (
ID BIGINT AUTO_INCREMENT,
PRODUTO VARCHAR (25),
ASPECTO VARCHAR (30),
MARCA VARCHAR (25),
PRECO INT,
TIPO_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (TIPO_ID) REFERENCES TB_CATEGORIAS (ID)
);

INSERT INTO TB_CATEGORIAS (COSMETICO, FUNCAO)
VALUES ("Maquiagem","Estetica");
INSERT INTO TB_CATEGORIAS (COSMETICO, FUNCAO)
VALUES ("Banho","Higiene pessoal");
INSERT INTO TB_CATEGORIAS (COSMETICO, FUNCAO)
VALUES ("Creme facial/corporal","Restaurador");
INSERT INTO TB_CATEGORIAS (COSMETICO, FUNCAO)
VALUES ("Desodorante","Antitranspirante");
INSERT INTO TB_CATEGORIAS (COSMETICO, FUNCAO)
VALUES ("Produtos infantis","Higiene pessoal para criancas");

INSERT INTO TB_PRODUTOS (PRODUTO, ASPECTO, MARCA, PRECO, TIPO_ID)
VALUES ("Batom","Matte","Kylie Cosmetics", 150.00, 1);
INSERT INTO TB_PRODUTOS (PRODUTO, ASPECTO, MARCA, PRECO, TIPO_ID)
VALUES ("Sabonete","Destinado a pele ressecada","Nivea", 35.00, 2);
INSERT INTO TB_PRODUTOS (PRODUTO, ASPECTO, MARCA, PRECO, TIPO_ID)
VALUES ("Shampoo Infantil", "PH balanceado","Johnsons Baby", 29.00, 5);
INSERT INTO TB_PRODUTOS (PRODUTO, ASPECTO, MARCA, PRECO, TIPO_ID)
VALUES ("Creme corporal","Hidratacao para pele ressecada","Neutrogena", 39.00, 3);
INSERT INTO TB_PRODUTOS (PRODUTO, ASPECTO, MARCA, PRECO, TIPO_ID)
VALUES ("Base Liquida","A prova dagua","Boca Rosa", 95.00, 1);
INSERT INTO TB_PRODUTOS (PRODUTO, ASPECTO, MARCA, PRECO, TIPO_ID)
VALUES ("Desodorante","Longa duracao","Rexona", 23.00, 4);
INSERT INTO TB_PRODUTOS (PRODUTO, ASPECTO, MARCA, PRECO, TIPO_ID)
VALUES ("Condicionador", "Vegano", "Skala", 11.00, 2);
INSERT INTO TB_PRODUTOS (PRODUTO, ASPECTO, MARCA, PRECO, TIPO_ID)
VALUES ("Deliniador","Resistente a agua","Ruby Rose", 15.00, 1);

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50.00;
SELECT * FROM TB_PRODUTOS WHERE PRECO > 5.00 AND PRECO < 60.00;
SELECT * FROM TB_PRODUTOS WHERE PRODUTO LIKE "%C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.TIPO_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.TIPO_ID = TB_CATEGORIAS.ID WHERE TB_PRODUTOS.TIPO_ID = 3;